apiVersion: v1
kind: ConfigMap
metadata:
  name: casestudy-calcandofferservice-config-map-v2
  labels:
    env: staging
    businessUnit: calculationsandoffersv2
data:
  ASPNETCORE_URLS: http://*:8080
  ASPNETCORE_ENVIRONMENT: Development
  MONGO_CONNECTION_STRING: mongodb://root:Prestige@mongodb-service:27017/

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: casestudy-calcandofferservice-deployment-v2
  labels:
    env: staging
    businessUnit: calculationsandoffersv2
spec:
  replicas: 2
  selector:
    matchExpressions:
    - {key: env, operator: In, values: ['staging']}
    - {key: businessUnit, operator: In, values: ['calculationsandoffersv2']}
  template:
    metadata:
      name: casestudy-calcandofferservice-podv2
      labels:
        env: staging
        businessUnit: calculationsandoffersv2
    spec:
      containers:
      - name: casestudy-calcandofferservice-containerv2
        image: 142198642907.dkr.ecr.ap-south-1.amazonaws.com/ramkumar-casestudy-calculation-service:v2
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: casestudy-calcandofferservice-config-map-v2
              key: ASPNETCORE_URLS
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: casestudy-calcandofferservice-config-map-v2
              key: ASPNETCORE_ENVIRONMENT
        - name: MONGO_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: casestudy-calcandofferservice-config-map-v2
              key: MONGO_CONNECTION_STRING

---

apiVersion: v1
kind: Service
metadata:
  name: casestudy-calcandofferservice-servicev2
  labels:
    env: staging
    businessUnit: calculationsandoffersv2
spec:
  type: ClusterIP
  ports:
  - targetPort: 8080
    port: 8080
  selector:
    env: staging
    businessUnit: calculationsandoffersv2

        