apiVersion: v1
kind: ConfigMap
metadata:
  name: casestudy-calcandofferservice-config-map
  labels:
    env: staging
    businessUnit: calculationsandoffers
data:
  MONGO_CONNECTION_STRING: {{ .Values.configuration.MONGO_CONNECTION_STRING }}
  ASPNETCORE_URLS: {{ .Values.configuration.ASPNETCORE_URLS }}
  ASPNETCORE_ENVIRONMENT: {{ .Values.configuration.ASPNETCORE_ENVIRONMENT }}
