apiVersion: v1
kind: Service
metadata:
  name: casestudy-calcandofferservice-service
  labels:
    env: staging
    businessUnit: calculationsandoffers
spec:
  type: {{ .Values.service.type }}
  ports:
    - targetPort: {{ .Values.container.port }}
      port: {{ .Values.service.port }}
  selector:
    env: staging
    businessUnit: calculationsandoffers
