apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    env: staging
    businessUnit: database
data:
  MONGO_INITDB_ROOT_PASSWORD: UHJlc3RpZ2U=
stringData:
  MONGO_INITDB_ROOT_USERNAME: root

---      

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-deployment
  labels:
    env: staging
    businessUnit: database
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      env: staging
      businessUnit: database
      app: mongodb
  template:      
    metadata:
      labels:
        env: staging
        businessUnit: database
        app: mongodb  
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: db
        image: mongo
        ports:
          - containerPort: 27017
        envFrom:
          - secretRef:
              name: mongodb-secret
        volumeMounts:
          - name: mongo-persistent-volume
            mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
          
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017  