apiVersion: v1
kind: ConfigMap
metadata:
  name: casestudy-calcandofferservice-config-map
  labels:
    env: staging
    businessUnit: calculationsandoffers
data:
  MONGO_CONNECTION_STRING: mongodb://root:Prestige@mongodb-service:27017/
  ASPNETCORE_URLS: http://*:8080
  ASPNETCORE_ENVIRONMENT: Development

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: casestudy-calcandofferservice-deployment
  labels:
    env: staging
    businessUnit: calculationsandoffers
spec:
  replicas: 2
  selector:
    matchExpressions:
    - {key: env, operator: In, values: ['staging']}
    - {key: businessUnit, operator: In, values: ['calculationsandoffers']}
  template:
    metadata:
      name: casestudy-calcandofferservice-pod
      labels:
        env: staging
        businessUnit: calculationsandoffers
    spec:
      containers:
      - name: casestudy-calcandofferservice-container
        image: 142198642907.dkr.ecr.ap-south-1.amazonaws.com/ramkumar-casestudy-calculation-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: casestudy-calcandofferservice-config-map
              key: ASPNETCORE_URLS
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: casestudy-calcandofferservice-config-map
              key: ASPNETCORE_ENVIRONMENT
        - name: MONGO_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: casestudy-calcandofferservice-config-map
              key: MONGO_CONNECTION_STRING

---

apiVersion: v1
kind: Service
metadata:
  name: casestudy-calcandofferservice-service
  labels:
    env: staging
    businessUnit: calculationsandoffers
spec:
  type: ClusterIP
  ports:
  - targetPort: 8080
    port: 8080
  selector:
    env: staging
    businessUnit: calculationsandoffers

        