apiVersion: v1
kind: ConfigMap
metadata:
  name: casestudy-identity-verification-response-service-config-map
  labels:
    env: staging
    businessUnit: identity-verification-response-service
data:
  CLOUDAMQP_URL: amqp://guest:guest@rabbitmq:5672/
  VERIFICATION_RESPONSE_QUEUE: verification-outputs-queue

---

apiVersion: v1
kind: Secret
metadata:
  name: casestudy-identity-verification-response-service-secret
  labels:
    env: staging
    businessUnit: identity-verification-response-service
data:
  MONGO_CONNECTION_STRING: bW9uZ29kYjovL3Jvb3Q6UHJlc3RpZ2VAbW9uZ29kYi1zZXJ2aWNlOjI3MDE3Lw==

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: casestudy-identity-verification-response-service
  labels:
    env: staging
    businessUnit: identity-verification-response-service
spec:
  replicas: 1
  selector:
    matchExpressions:
    - {key: env, operator: In, values: ['staging']}
    - {key: businessUnit, operator: In, values: ['identity-verification-response-service']}
  template:
    metadata:
      name: casestudy-identity-verification-response-service-pod
      labels:
        env: staging
        businessUnit: identity-verification-response-service
    spec:
      containers:
      - name: casestudy-identity-verification-response-service-container
        image: 142198642907.dkr.ecr.ap-south-1.amazonaws.com/ramkumar-casestudy-identity-verification-response-daemon:latest
        env:
        - name: CLOUDAMQP_URL
          valueFrom:
            configMapKeyRef:
              name: casestudy-identity-verification-response-service-config-map
              key: CLOUDAMQP_URL
        - name: MONGO_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: casestudy-identity-verification-response-service-secret
              key: MONGO_CONNECTION_STRING
        - name: VERIFICATION_RESPONSE_QUEUE
          valueFrom:
            configMapKeyRef:
              name: casestudy-identity-verification-response-service-config-map
              key: VERIFICATION_RESPONSE_QUEUE
