apiVersion: v1
kind: ConfigMap
metadata:
  name: casestudy-emailservice-config-map
  labels:
    env: staging
    businessUnit: emailservice
data:
  CLOUDAMQP_URL: amqp://guest:guest@rabbitmq:5672/
  AWS_REGION: ap-south-1
  MONGO_CONNECTION_STRING: mongodb://root:Prestige@mongodb-service:27017/
  EMAIL_REQUESTS_QUEUE: email-requests-queue
  SMTP_HOST: mailhog
  SMTP_PORT: "1025"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: casestudy-emailservice
  labels:
    env: staging
    businessUnit: emailservice
spec:
  replicas: 1
  selector:
    matchExpressions:
    - {key: env, operator: In, values: ['staging']}
    - {key: businessUnit, operator: In, values: ['emailService']}
  template:
    metadata:
      name: casestudy-emailservice-pod
      labels:
        env: staging
        businessUnit: emailService
    spec:
      containers:
      - name: casestudy-emailservice-container
        image: 142198642907.dkr.ecr.ap-south-1.amazonaws.com/ramkumar-casestudy-email-service:latest
        env:
        - name: CLOUDAMQP_URL
          valueFrom:
            configMapKeyRef:
              name: casestudy-emailservice-config-map
              key: CLOUDAMQP_URL
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: casestudy-emailservice-config-map
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: casestudy-emailservice-config-map
              key: SMTP_PORT   
        - name: MONGO_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: casestudy-emailservice-config-map
              key: MONGO_CONNECTION_STRING
        - name: EMAIL_REQUESTS_QUEUE
          valueFrom:
            configMapKeyRef:
              name: casestudy-emailservice-config-map
              key: EMAIL_REQUESTS_QUEUE                  
  