apiVersion: apps/v1
kind: Deployment
metadata:
  name: casestudy-identity-verification-response-service
  labels:
    env: staging
    businessUnit: identity-verification-response-service
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchExpressions:
    - {key: env, operator: In, values: ['staging']}
    - {key: businessUnit, operator: In, values: ['identity-verification-response-service']}
  template:
    metadata:
      name: casestudy-identity-verification-response-service-pod
      labels:
        env: staging
        businessUnit: identity-verification-response-service
    spec:
      containers:
      - name: casestudy-identity-verification-response-service-container
        image: {{ .Values.container.image }}
        env:
        - name: CLOUDAMQP_URL
          valueFrom:
            configMapKeyRef:
              name: casestudy-identity-verification-response-service-config-map
              key: CLOUDAMQP_URL
        - name: MONGO_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: casestudy-identity-verification-response-service-secret
              key: MONGO_CONNECTION_STRING
        - name: VERIFICATION_RESPONSE_QUEUE
          valueFrom:
            configMapKeyRef:
              name: casestudy-identity-verification-response-service-config-map
              key: VERIFICATION_RESPONSE_QUEUE
