apiVersion: v1
kind: Secret
metadata:
  name: casestudy-creditcard-service-secret
  labels:
    env: staging
    businessUnit: creditcard-service
data:
  MONGO_CONNECTION_STRING: {{ .Values.secret.MONGO_CONNECTION_STRING }}