apiVersion: v1
kind: Service
metadata:
  name: casestudy-creditcard-service-service
  labels:
    env: staging
    businessUnit: creditcards
spec:
  type: {{ .Values.service.type }}
  ports:
  - targetPort: {{ .Values.container.port }}
    port: {{ .Values.service.port }}
  selector:
    env: staging
    businessUnit: creditcards

