apiVersion: v1
kind: ConfigMap
metadata:
  name: casestudy-identity-verification-service-config-map
  labels:
    env: staging
    businessUnit: identity-verification-service
data:
  CLOUDAMQP_URL: {{ .Values.configuration.CLOUDAMQP_URL }}
  INPUT_QUEUE: {{ .Values.configuration.INPUT_QUEUE }}
  RESPONSE_QUEUE: {{ .Values.configuration.RESPONSE_QUEUE }}
