apiVersion: v1
kind: ConfigMap
metadata:
  name: casestudy-emailservice-config-map
  labels:
    env: staging
    businessUnit: emailservice
data:
  CLOUDAMQP_URL: amqp://guest:guest@rabbitmq:5672/
  AWS_REGION: ap-south-1
  MONGO_CONNECTION_STRING: mongodb://root:Prestige@mongodb-service:27017/
  EMAIL_REQUESTS_QUEUE: email-requests-queue

---

apiVersion: v1
kind: Secret
metadata:
  name: casestudy-emailservice-secret
  labels:
    env: staging
    businessUnit: emailService
data:
  AWS_ACCESS_KEY: QUtJQVNDRzVUREROV1UzUUFCN0U=
  AWS_ACCESS_SECRET_KEY: bmtrYU4wMW9MenZpYjBDT2NWenozQnFzK3YyVFNDNUJjeVFnU1lVSA==
  
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: casestudy-emailservice
  labels:
    env: staging
    businessUnit: emailservice
spec:
  replicas: 1
  selector:
    matchExpressions:
    - {key: env, operator: In, values: ['staging']}
    - {key: businessUnit, operator: In, values: ['emailService']}
  template:
    metadata:
      name: casestudy-emailservice-pod
      labels:
        env: staging
        businessUnit: emailService
    spec:
      containers:
      - name: casestudy-emailservice-container
        image: iomega/casestudy-email-service
        env:
        - name: CLOUDAMQP_URL
          valueFrom:
            configMapKeyRef:
              name: casestudy-emailservice-config-map
              key: CLOUDAMQP_URL
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: casestudy-emailservice-secret
              key: AWS_ACCESS_KEY
        - name: AWS_ACCESS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: casestudy-emailservice-secret
              key: AWS_ACCESS_SECRET_KEY   
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: casestudy-emailservice-config-map
              key: AWS_REGION                 
        - name: MONGO_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: casestudy-emailservice-config-map
              key: MONGO_CONNECTION_STRING
        - name: EMAIL_REQUESTS_QUEUE
          valueFrom:
            configMapKeyRef:
              name: casestudy-emailservice-config-map
              key: EMAIL_REQUESTS_QUEUE                  
        volumeMounts:
        - name: foo
          mountPath: /etc/foo
          readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: casestudy-emailservice-secret       