apiVersion: v1
kind: ConfigMap
metadata:
  name: casestudy-creditcard-service-config-map
  labels:
    env: staging
    businessUnit: creditcards
data:
  FLASK_APP: ./api.py
  CLOUDAMQP_URL: amqp://guest:guest@rabbitmq:5672/
  CALCULATION_SERVICE_URL: http://casestudy-calcandofferservice-service:8080/api/calculation-services/process
  VERIFICATION_INPUTS_QUEUE: verification-inputs-queue
  EMAIL_REQUESTS_QUEUE: email-requests-queue
  FROM_EMAIL_ADDRESS: iomega.azure@gmail.com
  FLASK_DEBUG: "true"
  FLASK_ENV: "development"
  FLASK_RUN_PORT: "80"

---

apiVersion: v1
kind: Secret
metadata:
  name: casestudy-creditcard-service-secret
  labels:
    env: staging
    businessUnit: creditcard-service
data:
  MONGO_CONNECTION_STRING: bW9uZ29kYjovL3Jvb3Q6UHJlc3RpZ2VAbW9uZ29kYi1zZXJ2aWNlOjI3MDE3Lw==

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: casestudy-creditcard-service-deployment
  labels:
    env: staging
    businessUnit: creditcards
spec:
  replicas: 1
  selector:
    matchExpressions:
    - {key: env, operator: In, values: ['staging']}
    - {key: businessUnit, operator: In, values: ['creditcards']}
  template:
    metadata:
      name: casestudy-creditcard-service-pod
      labels:
        env: staging
        businessUnit: creditcards
    spec:
      containers:
      - name: casestudy-creditcard-service-container
        image: iomega/ms-casestudy-creditcard-service
        ports:
        - containerPort: 80
        env:
        - name: FLASK_DEBUG
          valueFrom:
            configMapKeyRef:
              name: casestudy-creditcard-service-config-map
              key: FLASK_DEBUG
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: casestudy-creditcard-service-config-map
              key: FLASK_ENV
        - name: MONGO_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: casestudy-creditcard-service-secret
              key: MONGO_CONNECTION_STRING
        - name: FLASK_RUN_PORT
          valueFrom:
            configMapKeyRef:
              name: casestudy-creditcard-service-config-map
              key: FLASK_RUN_PORT
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              name: casestudy-creditcard-service-config-map
              key: FLASK_APP
        - name: CLOUDAMQP_URL
          valueFrom:
            configMapKeyRef:
              name: casestudy-creditcard-service-config-map
              key: CLOUDAMQP_URL
        - name: CALCULATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: casestudy-creditcard-service-config-map
              key: CALCULATION_SERVICE_URL
        - name: VERIFICATION_INPUTS_QUEUE
          valueFrom:
            configMapKeyRef:
              name: casestudy-creditcard-service-config-map
              key: VERIFICATION_INPUTS_QUEUE
        - name: EMAIL_REQUESTS_QUEUE
          valueFrom:
            configMapKeyRef:
              name: casestudy-creditcard-service-config-map
              key: EMAIL_REQUESTS_QUEUE
        - name: FROM_EMAIL_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: casestudy-creditcard-service-config-map
              key: FROM_EMAIL_ADDRESS
             
---

apiVersion: v1
kind: Service
metadata:
  name: casestudy-creditcard-service-service
  labels:
    env: staging
    businessUnit: creditcards
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
  selector:
    env: staging
    businessUnit: creditcards

        