apiVersion: v1
kind: ConfigMap
metadata:
  name: casestudy-identity-verification-service-config-map
  labels:
    env: staging
    businessUnit: identity-verification-service
data:
  CLOUDAMQP_URL: amqp://guest:guest@rabbitmq:5672/
  INPUT_QUEUE: verification-inputs-queue
  RESPONSE_QUEUE: verification-outputs-queue

---

apiVersion: v1
kind: Secret
metadata:
  name: casestudy-identity-verification-service-secret
  labels:
    env: staging
    businessUnit: identity-verification-service
data:
  MONGO_CONNECTION_STRING: bW9uZ29kYjovL3Jvb3Q6UHJlc3RpZ2VAbW9uZ29kYi1zZXJ2aWNlOjI3MDE3Lw==

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: casestudy-identity-verification-service
  labels:
    env: staging
    businessUnit: identity-verification-service
spec:
  replicas: 1
  selector:
    matchExpressions:
    - {key: env, operator: In, values: ['staging']}
    - {key: businessUnit, operator: In, values: ['identity-verification-service']}
  template:
    metadata:
      name: casestudy-identity-verification-service-pod
      labels:
        env: staging
        businessUnit: identity-verification-service
    spec:
      containers:
      - name: casestudy-identity-verification-service-container
        image: iomega/ms-casestudy-identity-verification-service
        env:
        - name: CLOUDAMQP_URL
          valueFrom:
            configMapKeyRef:
              name: casestudy-identity-verification-service-config-map
              key: CLOUDAMQP_URL
        - name: MONGO_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: casestudy-identity-verification-service-secret
              key: MONGO_CONNECTION_STRING
        - name: RESPONSE_QUEUE
          valueFrom:
            configMapKeyRef:
              name: casestudy-identity-verification-service-config-map
              key: RESPONSE_QUEUE
        - name: INPUT_QUEUE
          valueFrom:
            configMapKeyRef:
              name: casestudy-identity-verification-service-config-map
              key: INPUT_QUEUE                  
        volumeMounts:
        - name: foo
          mountPath: /etc/foo
          readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: casestudy-identity-verification-service-secret       