apiVersion: v1
kind: PersistentVolume
metadata:
  name: iomegaazurefile
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: vol-uniq-id-001
    volumeAttributes:
      resourceGroup: casestudyresourcegroup
      shareName: iomegafileshare
    nodeStageSecretRef:
      name: azure-secret
      namespace: casestudy
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iomegaazurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
