apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    env: staging
    businessUnit: database
data:
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.rootPassword }}
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secrets.rootUsername }}
