apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: {{ .Values.services.serviceType }}
  selector:
    app: mongodb
  ports:
  - protocol: {{ .Values.services.serviceProtocol }}
    port: {{ .Values.services.servicePort }}  